spring:
  profiles:
    include: secret
  application:
    name: moviegoer-backend
  datasource:
    url: jdbc:mysql://localhost:3307/moviegoer-db
    username: moviegoer-admin
    password: dev_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true